# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Importante
    url: tour
    weight: 10
  - name: Unidade
    url: unidade
    weight: 20
  - name: Notícias
    url: post
    weight: 30
  - name: Equipa
    url: people
    weight: 40
  - name: Eventos
    url: event
    weight: 50
  - name: Contactos
    url: contact
    weight: 60
