backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow
media_folder: "assets/media"

collections:
  - name: "unidade" 
    label: "Unidade" 
    folder: "content/unidade" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "content/unidade/{{slug}}" 
    fields: # The fields for each document, usually in front matter`
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "sections", widget: "markdown"}